/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as OperacaoIdRouteImport } from './routes/operacao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoIdRoute = OperacaoIdRouteImport.update({
  id: '/operacao/$id',
  path: '/operacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/entrada': typeof EntradaRoute
  '/estoque': typeof EstoqueRoute
  '/kits': typeof KitsRoute
  '/relatorio': typeof RelatorioRoute
  '/operacao/$id': typeof OperacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/entrada': typeof EntradaRoute
  '/estoque': typeof EstoqueRoute
  '/kits': typeof KitsRoute
  '/relatorio': typeof RelatorioRoute
  '/operacao/$id': typeof OperacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/entrada': typeof EntradaRoute
  '/estoque': typeof EstoqueRoute
  '/kits': typeof KitsRoute
  '/relatorio': typeof RelatorioRoute
  '/operacao/$id': typeof OperacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cronograma'
    | '/entrada'
    | '/estoque'
    | '/kits'
    | '/relatorio'
    | '/operacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cronograma'
    | '/entrada'
    | '/estoque'
    | '/kits'
    | '/relatorio'
    | '/operacao/$id'
  id:
    | '__root__'
    | '/'
    | '/cronograma'
    | '/entrada'
    | '/estoque'
    | '/kits'
    | '/relatorio'
    | '/operacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaRoute: typeof CronogramaRoute
  EntradaRoute: typeof EntradaRoute
  EstoqueRoute: typeof EstoqueRoute
  KitsRoute: typeof KitsRoute
  RelatorioRoute: typeof RelatorioRoute
  OperacaoIdRoute: typeof OperacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrada': {
      id: '/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof EntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/$id': {
      id: '/operacao/$id'
      path: '/operacao/$id'
      fullPath: '/operacao/$id'
      preLoaderRoute: typeof OperacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaRoute: CronogramaRoute,
  EntradaRoute: EntradaRoute,
  EstoqueRoute: EstoqueRoute,
  KitsRoute: KitsRoute,
  RelatorioRoute: RelatorioRoute,
  OperacaoIdRoute: OperacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
